os: linux
language: android
jdk: oraclejdk8
env:
  - TRAVIS_NODE_VERSION="10.16.3"
  - TRAVIS_NODE_VERSION="10"
android:
  components:
    - build-tools-28.0.3
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  # - nvm install && nvm use
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm ci
script:
  - "./android/gradlew assembleRelease -p android/"