# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_ios_screenshots(workspace: "ReactNativeTravisCI.xcworkspace", scheme: "ReactNativeTravisCI", devices: ["iPhone 8"])
  end
  lane :test do
    # https://docs.fastlane.tools/actions/scan/
    scan(
      workspace: "ReactNativeTravisCI.xcworkspace",
      scheme: "ReactNativeTravisCI"
    )
  end
end
